name = "alexmr-link"
main = "src/index.ts"
compatibility_date = "2024-11-01"

routes = [
  { pattern = "link.alexmr.me", custom_domain = true }
]

kv_namespaces = [
  { binding = "LINKS", id = "01d7c9d722de447fb0bb83b04e160772" }
]

[vars]
ADMIN_USERNAME = "admin"
# ADMIN_PASSWORD is a secret: set with `wrangler secret put ADMIN_PASSWORD`
